# Generated by Django 4.2.23 on 2025-08-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0002_trade_symbol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trade",
            name="large_timeframe_image",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="medium_timeframe_image",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="short_timeframe_image",
        ),
        migrations.AddField(
            model_name="trade",
            name="large_image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="large_image_content_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="large_image_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="medium_image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="medium_image_content_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="medium_image_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="short_image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="short_image_content_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="short_image_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
