# Generated by Django 4.2.23 on 2025-08-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_remove_trade_large_timeframe_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('crypto', 'Crypto'), ('forex', 'Forex'), ('index', 'Index')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('pre_session_todo', models.TextField(blank=True, help_text='Checklist before trading session')),
                ('trading_times', models.TextField(blank=True, help_text='Timings for trading (sessions, hours)')),
                ('tradable_news', models.TextField(blank=True, help_text='News/events we can trade')),
                ('avoid_news', models.TextField(blank=True, help_text='News/events to avoid')),
                ('setups', models.TextField(blank=True, help_text='Setups being used')),
                ('watchlist_pairs', models.TextField(blank=True, help_text='Pairs being watched')),
                ('position_management', models.TextField(blank=True, help_text='Position management information')),
                ('targets', models.TextField(blank=True, help_text='Targets and take-profit planning')),
                ('stop_rules', models.TextField(blank=True, help_text='Rules for when to stop trading')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['type', 'name'],
                'unique_together': {('type', 'name')},
            },
        ),
    ]
